name: Playwright Tests
on:
  push:

jobs:
  test-playwright:
    timeout-minutes: 60
    runs-on: self-hosted

    env:
      _DOMAIN: "dind"

    strategy:
      fail-fast: false
      matrix:
        include:
          - project: authoring_tool
          - project: backend_api
          - project: e2e
          - project: game

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker Compose config
        run: docker compose -f docker-compose.base.yml -f docker-compose.test-adjustments.yml config > docker-compose.yml

      - name: Start Docker services
        run: docker compose up -d --wait --timeout 600 --pull always --build

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
        working-directory: ./${{ matrix.project }}

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
        working-directory: ./${{ matrix.project }}

      - name: Run Playwright tests
        run: xvfb-run --server-args="-screen 0 1920x1080x24" npm test
        working-directory: ./${{ matrix.project }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.project }}
          path: ${{ matrix.project }}/playwright-report/
          retention-days: 30
